FROM node:24-slim

RUN apt update \
	&& apt install -y --no-install-recommends procps curl ffmpeg \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app

COPY package*.json ./

RUN npm ci \
	&& chown -R node:node /home/node/app

USER node

CMD [ "tail", "-f", "/dev/null" ] 